name: 'Docker Container Action'
description: 'A reimplementation of docker container action'
branding:
  icon: 'award'
  color: 'green'
inputs:
  repository:
    description: 'The GitHub repository name'
    required: true
  ref:
    description: 'The GitHub repository ref'
    required: true
  image:
    description: 'The docker image name (defaults to repository)'
    required: false
  tag:
    description: 'The docker image tag (defaults to ref)'
    required: false
  dockerfile:
    description: 'The dockerfile path'
    required: false
    default: 'Dockerfile'
  opts:
    description: 'The docker run opts'
    required: false
  args:
    description: 'The docker run args'
    required: false
  working-directory:
    description: 'The docker run working directory'
    required: false
    default: ${{ github.workspace }}
  github-server-url:
    description: 'The GitHub server URL'
    required: false
    default: ${{ github.server_url }}
  docker-registry-url:
    description: 'The docker registry URL'
    required: false
    default: 'https://ghcr.io'
outputs:
  outputs:
    description: 'The outputs of the docker run step in JSON format'
    value: ${{ toJSON(steps.run.outputs) }}
runs:
  using: 'composite'
  steps:
    - id: pull
      env:
        IMAGE: ${{ inputs.image || inputs.repository }}
        TAG: ${{ inputs.tag || inputs.ref }}
        DOCKER_REGISTRY_URL: ${{ inputs.docker-registry-url }}
      run: echo "exit=$(docker pull ${DOCKER_REGISTRY_URL#http*://}/$IMAGE:$TAG; echo $?)" >> $GITHUB_OUTPUT
      shell: bash
    - if: steps.pull.outputs.exit == 1
      env:
        REPOSITORY: ${{ inputs.repository }}
        REF: ${{ inputs.ref }}
        IMAGE: ${{ inputs.image || inputs.repository }}
        TAG: ${{ inputs.tag || inputs.ref }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        DOCKER_REGISTRY_URL: ${{ inputs.docker-registry-url }}
      run: docker build -t ${DOCKER_REGISTRY_URL#http*://}/$IMAGE:$TAG -f $DOCKERFILE $GITHUB_SERVER_URL/$REPOSITORY.git#$REF
      shell: bash
    - id: run
      env:
        DOCKER_REGISTRY_URL: ${{ inputs.docker-registry-url }}
        IMAGE: ${{ inputs.image || inputs.repository }}
        TAG: ${{ inputs.tag || inputs.ref }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_DOCKERFILE: ${{ inputs.dockerfile }}
        INPUT_OPTS: ${{ inputs.opts }}
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        INPUT_DOCKER_REGISTRY_URL: ${{ inputs.docker-registry-url }}
      run: docker run --workdir "${PWD/"$GITHUB_WORKSPACE"/"/github/workspace"}" --rm --env-file <(env | grep -E '^(ACTIONS|GITHUB|INPUT|RUNNER)_') -e HOME -e CI -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "$GITHUB_WORKSPACE":"/github/workspace" ${{ inputs.opts }} "${DOCKER_REGISTRY_URL#http*://}/$IMAGE:$TAG" ${{ inputs.args }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
